format = """[→](bold cyan) $directory$git_branch$git_commit$git_state$git_metrics$git_status$time
$all"""

[directory]
# truncation_length = 10

[git_branch]
truncation_length = 50

[battery]
disabled = true

[time]
disabled = false

[aws]
symbol = '󰸏 '

[gcloud]
format = '[$symbol$region]($style) '
symbol = ' '
